### ISSUE TITLE
Spikestrip Content not loading.

### ISSUE THREAD

**Issue by Coffe-e** [prodzpod/ProdzpodSpikestripContent#2] opened 2024-09-24 04:48 UTC
Tried this both in my 160+ modpack and standalone w/ debugtoolkit, no luck. Here's the log for the standalone one.
[LogOutput.log](https://github.com/user-attachments/files/17108124/LogOutput.log)

**Comment by Fooshcookie** [comment] 2024-09-24 05:26
Being worked on. Dupe of #1, my first log. Working with prod as we speak to not only fix the current version issue, but also fix it strangely failing even with corrections on my machine.

**Comment by prodzpod** [comment] 2024-09-24 08:55
#1

**Closed as completed by prodzpod** 2024-09-24 08:55 UTC
